/* Generated by genstub.  Do not edit. */
#include <gauche.h>

#line 6 "./jwteclib.stub"
#include "jwtec.h"


static ScmObj jwteclib_test_jwtec(ScmObj*, int, void*);
static SCM_DEFINE_SUBRX(jwteclib_test_jwtec__STUB, 0, 0,0, SCM_FALSE,SCM_SUBR_IMMEDIATE_ARG, jwteclib_test_jwtec, NULL, NULL);

#if defined(__CYGWIN__) || defined(GAUCHE_WINDOWS)
#define SCM_CGEN_CONST /*empty*/
#else
#define SCM_CGEN_CONST const
#endif
static SCM_CGEN_CONST struct scm__scRec {
  ScmString d1698[3];
} scm__sc SCM_UNUSED = {
  {   /* ScmString d1698 */
      SCM_STRING_CONST_INITIALIZER("test-jwtec", 10, 10),
      SCM_STRING_CONST_INITIALIZER("source-info", 11, 11),
      SCM_STRING_CONST_INITIALIZER("./jwteclib.stub", 15, 15),
  },
};
static struct scm__rcRec {
  ScmObj d1699[11];
} scm__rc SCM_UNUSED = {
  {   /* ScmObj d1699 */
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_MAKE_INT(11U),
    SCM_NIL,
    SCM_OBJ(&scm__sc.d1698[2]),
    SCM_OBJ(&scm__rc.d1699[2]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[4]),
    SCM_OBJ(&scm__rc.d1699[6]),
    SCM_NIL,
    SCM_UNBOUND,
  },
};
static ScmObj jwteclib_test_jwtec(ScmObj *SCM_FP SCM_UNUSED, int SCM_ARGCNT SCM_UNUSED, void *data_ SCM_UNUSED)
{
  SCM_ENTER_SUBR("test-jwtec");
  {
{
const char * SCM_RESULT;

#line 12 "./jwteclib.stub"
SCM_RESULT=("jwtec is working");
goto SCM_STUB_RETURN;
SCM_STUB_RETURN:
SCM_RETURN(SCM_MAKE_STR_COPYING(SCM_RESULT));
}
  }
}

void Scm_Init_jwteclib(ScmModule *mod SCM_UNUSED){

  scm__rc.d1699[0] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[0])),TRUE); /* test-jwtec */
  scm__rc.d1699[1] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[1])),TRUE); /* source-info */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[6]), scm__rc.d1699[1]);
  scm__rc.d1699[10] = Scm_MakeExtendedPair(scm__rc.d1699[0], SCM_NIL, SCM_OBJ(&scm__rc.d1699[8]));
  Scm_MakeBinding(SCM_MODULE(mod), SCM_SYMBOL(SCM_INTERN("test-jwtec")), SCM_OBJ(&jwteclib_test_jwtec__STUB), 0);
  jwteclib_test_jwtec__STUB.common.info = scm__rc.d1699[10];
}
