/* Generated by genstub.  Do not edit. */
#include <gauche.h>

#line 6 "./jwteclib.stub"
#include <openssl/ecdsa.h>


#line 7 "./jwteclib.stub"
#include "jwtec.h"


static ScmObj jwteclib_do_sign(ScmObj*, int, void*);
static SCM_DEFINE_SUBRX(jwteclib_do_sign__STUB, 3, 0,0, SCM_FALSE,SCM_SUBR_IMMEDIATE_ARG, jwteclib_do_sign, NULL, NULL);


static ScmObj jwteclib_do_verify(ScmObj*, int, void*);
static SCM_DEFINE_SUBRX(jwteclib_do_verify__STUB, 6, 0,0, SCM_FALSE,SCM_SUBR_IMMEDIATE_ARG, jwteclib_do_verify, NULL, NULL);


static ScmObj jwteclib_list_builtin_curves(ScmObj*, int, void*);
static SCM_DEFINE_SUBRX(jwteclib_list_builtin_curves__STUB, 0, 0,0, SCM_FALSE,SCM_SUBR_IMMEDIATE_ARG, jwteclib_list_builtin_curves, NULL, NULL);


static ScmObj jwteclib_test_pass_arg(ScmObj*, int, void*);
static SCM_DEFINE_SUBRX(jwteclib_test_pass_arg__STUB, 2, 0,0, SCM_FALSE,SCM_SUBR_IMMEDIATE_ARG, jwteclib_test_pass_arg, NULL, NULL);

#if defined(__CYGWIN__) || defined(GAUCHE_WINDOWS)
#define SCM_CGEN_CONST /*empty*/
#else
#define SCM_CGEN_CONST const
#endif
static SCM_CGEN_CONST struct scm__scRec {
  ScmString d1698[15];
} scm__sc SCM_UNUSED = {
  {   /* ScmString d1698 */
      SCM_STRING_CONST_INITIALIZER("do-sign", 7, 7),
      SCM_STRING_CONST_INITIALIZER("curve-type", 10, 10),
      SCM_STRING_CONST_INITIALIZER("body", 4, 4),
      SCM_STRING_CONST_INITIALIZER("d", 1, 1),
      SCM_STRING_CONST_INITIALIZER("source-info", 11, 11),
      SCM_STRING_CONST_INITIALIZER("./jwteclib.stub", 15, 15),
      SCM_STRING_CONST_INITIALIZER("do-verify", 9, 9),
      SCM_STRING_CONST_INITIALIZER("dgst", 4, 4),
      SCM_STRING_CONST_INITIALIZER("r", 1, 1),
      SCM_STRING_CONST_INITIALIZER("s", 1, 1),
      SCM_STRING_CONST_INITIALIZER("x", 1, 1),
      SCM_STRING_CONST_INITIALIZER("y", 1, 1),
      SCM_STRING_CONST_INITIALIZER("list-builtin-curves", 19, 19),
      SCM_STRING_CONST_INITIALIZER("test-pass-arg", 13, 13),
      SCM_STRING_CONST_INITIALIZER("bn", 2, 2),
  },
};
static struct scm__rcRec {
  ScmObj d1699[72];
} scm__rc SCM_UNUSED = {
  {   /* ScmObj d1699 */
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNDEFINED,
    SCM_NIL,
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[4]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[6]),
    SCM_UNBOUND,
    SCM_MAKE_INT(10U),
    SCM_NIL,
    SCM_OBJ(&scm__sc.d1698[5]),
    SCM_OBJ(&scm__rc.d1699[11]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[13]),
    SCM_OBJ(&scm__rc.d1699[15]),
    SCM_NIL,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNDEFINED,
    SCM_NIL,
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[26]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[28]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[30]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[32]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[34]),
    SCM_MAKE_INT(14U),
    SCM_NIL,
    SCM_OBJ(&scm__sc.d1698[5]),
    SCM_OBJ(&scm__rc.d1699[38]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[40]),
    SCM_OBJ(&scm__rc.d1699[42]),
    SCM_NIL,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_MAKE_INT(19U),
    SCM_NIL,
    SCM_OBJ(&scm__sc.d1698[5]),
    SCM_OBJ(&scm__rc.d1699[48]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[50]),
    SCM_OBJ(&scm__rc.d1699[52]),
    SCM_NIL,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNBOUND,
    SCM_UNDEFINED,
    SCM_NIL,
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[59]),
    SCM_MAKE_INT(22U),
    SCM_NIL,
    SCM_OBJ(&scm__sc.d1698[5]),
    SCM_OBJ(&scm__rc.d1699[63]),
    SCM_UNDEFINED,
    SCM_OBJ(&scm__rc.d1699[65]),
    SCM_OBJ(&scm__rc.d1699[67]),
    SCM_NIL,
    SCM_UNBOUND,
  },
};
static ScmObj jwteclib_do_sign(ScmObj *SCM_FP SCM_UNUSED, int SCM_ARGCNT SCM_UNUSED, void *data_ SCM_UNUSED)
{
  ScmObj curve_type_scm;
  ScmString* curve_type;
  ScmObj body_scm;
  ScmUVector* body;
  ScmObj d_scm;
  ScmUVector* d;
  ScmObj SCM_SUBRARGS[3];
  SCM_ENTER_SUBR("do-sign");
  for (int SCM_i=0; SCM_i<3; SCM_i++) {
    SCM_SUBRARGS[SCM_i] = SCM_ARGREF(SCM_i);
  }
  curve_type_scm = SCM_SUBRARGS[0];
  if (!SCM_STRINGP(curve_type_scm)) Scm_Error("string required, but got %S", curve_type_scm);
  curve_type = SCM_STRING(curve_type_scm);
  body_scm = SCM_SUBRARGS[1];
  if (!SCM_U8VECTORP(body_scm)) Scm_Error("u8vector required, but got %S", body_scm);
  body = SCM_U8VECTOR(body_scm);
  d_scm = SCM_SUBRARGS[2];
  if (!SCM_U8VECTORP(d_scm)) Scm_Error("u8vector required, but got %S", d_scm);
  d = SCM_U8VECTOR(d_scm);
  {
{
ScmString* SCM_RESULT;

#line 11 "./jwteclib.stub"
{SCM_RESULT=(
SCM_STRING(signWithKey(Scm_GetStringConst(curve_type),body,d)));goto SCM_STUB_RETURN;}
goto SCM_STUB_RETURN;
SCM_STUB_RETURN:
SCM_RETURN(SCM_OBJ_SAFE(SCM_RESULT));
}
  }
}

static ScmObj jwteclib_do_verify(ScmObj *SCM_FP SCM_UNUSED, int SCM_ARGCNT SCM_UNUSED, void *data_ SCM_UNUSED)
{
  ScmObj curve_type_scm;
  ScmString* curve_type;
  ScmObj dgst_scm;
  ScmUVector* dgst;
  ScmObj r_scm;
  ScmUVector* r;
  ScmObj s_scm;
  ScmUVector* s;
  ScmObj x_scm;
  ScmUVector* x;
  ScmObj y_scm;
  ScmUVector* y;
  ScmObj SCM_SUBRARGS[6];
  SCM_ENTER_SUBR("do-verify");
  for (int SCM_i=0; SCM_i<6; SCM_i++) {
    SCM_SUBRARGS[SCM_i] = SCM_ARGREF(SCM_i);
  }
  curve_type_scm = SCM_SUBRARGS[0];
  if (!SCM_STRINGP(curve_type_scm)) Scm_Error("string required, but got %S", curve_type_scm);
  curve_type = SCM_STRING(curve_type_scm);
  dgst_scm = SCM_SUBRARGS[1];
  if (!SCM_U8VECTORP(dgst_scm)) Scm_Error("u8vector required, but got %S", dgst_scm);
  dgst = SCM_U8VECTOR(dgst_scm);
  r_scm = SCM_SUBRARGS[2];
  if (!SCM_U8VECTORP(r_scm)) Scm_Error("u8vector required, but got %S", r_scm);
  r = SCM_U8VECTOR(r_scm);
  s_scm = SCM_SUBRARGS[3];
  if (!SCM_U8VECTORP(s_scm)) Scm_Error("u8vector required, but got %S", s_scm);
  s = SCM_U8VECTOR(s_scm);
  x_scm = SCM_SUBRARGS[4];
  if (!SCM_U8VECTORP(x_scm)) Scm_Error("u8vector required, but got %S", x_scm);
  x = SCM_U8VECTOR(x_scm);
  y_scm = SCM_SUBRARGS[5];
  if (!SCM_U8VECTORP(y_scm)) Scm_Error("u8vector required, but got %S", y_scm);
  y = SCM_U8VECTOR(y_scm);
  {
{
ScmObj SCM_RESULT;

#line 15 "./jwteclib.stub"
{SCM_RESULT=(verifyByKey(Scm_GetStringConst(curve_type),dgst,r,s,x,y));goto SCM_STUB_RETURN;}
goto SCM_STUB_RETURN;
SCM_STUB_RETURN:
SCM_RETURN(SCM_OBJ_SAFE(SCM_RESULT));
}
  }
}

static ScmObj jwteclib_list_builtin_curves(ScmObj *SCM_FP SCM_UNUSED, int SCM_ARGCNT SCM_UNUSED, void *data_ SCM_UNUSED)
{
  SCM_ENTER_SUBR("list-builtin-curves");
  {
{
ScmObj SCM_RESULT;

#line 20 "./jwteclib.stub"
{SCM_RESULT=(getBuiltinCurves());goto SCM_STUB_RETURN;}
goto SCM_STUB_RETURN;
SCM_STUB_RETURN:
SCM_RETURN(SCM_OBJ_SAFE(SCM_RESULT));
}
  }
}

static ScmObj jwteclib_test_pass_arg(ScmObj *SCM_FP SCM_UNUSED, int SCM_ARGCNT SCM_UNUSED, void *data_ SCM_UNUSED)
{
  ScmObj s_scm;
  ScmString* s;
  ScmObj bn_scm;
  ScmUVector* bn;
  ScmObj SCM_SUBRARGS[2];
  SCM_ENTER_SUBR("test-pass-arg");
  for (int SCM_i=0; SCM_i<2; SCM_i++) {
    SCM_SUBRARGS[SCM_i] = SCM_ARGREF(SCM_i);
  }
  s_scm = SCM_SUBRARGS[0];
  if (!SCM_STRINGP(s_scm)) Scm_Error("string required, but got %S", s_scm);
  s = SCM_STRING(s_scm);
  bn_scm = SCM_SUBRARGS[1];
  if (!SCM_U8VECTORP(bn_scm)) Scm_Error("u8vector required, but got %S", bn_scm);
  bn = SCM_U8VECTOR(bn_scm);
  {
{
ScmPair* SCM_RESULT;

#line 23 "./jwteclib.stub"
{uint8_t * cp=SCM_UVECTOR_ELEMENTS(bn);int size=
#line 25 "./jwteclib.stub"
Scm_UVectorSizeInBytes(bn);
{SCM_RESULT=(SCM_PAIR(SCM_LIST3(
SCM_OBJ(s),
Scm_MakeU8VectorFromArray(size,cp),
Scm_MakeInteger(size))));goto SCM_STUB_RETURN;}}
goto SCM_STUB_RETURN;
SCM_STUB_RETURN:
SCM_RETURN(SCM_OBJ(SCM_RESULT));
}
  }
}

void Scm_Init_jwteclib(ScmModule *mod SCM_UNUSED){

  scm__rc.d1699[0] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[0])),TRUE); /* do-sign */
  scm__rc.d1699[1] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[1])),TRUE); /* curve-type */
  scm__rc.d1699[2] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[2])),TRUE); /* body */
  scm__rc.d1699[3] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[3])),TRUE); /* d */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[4]), scm__rc.d1699[3]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[6]), scm__rc.d1699[2]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[8]), scm__rc.d1699[1]);
  scm__rc.d1699[10] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[4])),TRUE); /* source-info */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[15]), scm__rc.d1699[10]);
  scm__rc.d1699[19] = Scm_MakeExtendedPair(scm__rc.d1699[0], SCM_OBJ(&scm__rc.d1699[8]), SCM_OBJ(&scm__rc.d1699[17]));
  Scm_MakeBinding(SCM_MODULE(mod), SCM_SYMBOL(SCM_INTERN("do-sign")), SCM_OBJ(&jwteclib_do_sign__STUB), 0);
  jwteclib_do_sign__STUB.common.info = scm__rc.d1699[19];
  scm__rc.d1699[20] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[6])),TRUE); /* do-verify */
  scm__rc.d1699[21] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[7])),TRUE); /* dgst */
  scm__rc.d1699[22] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[8])),TRUE); /* r */
  scm__rc.d1699[23] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[9])),TRUE); /* s */
  scm__rc.d1699[24] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[10])),TRUE); /* x */
  scm__rc.d1699[25] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[11])),TRUE); /* y */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[26]), scm__rc.d1699[25]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[28]), scm__rc.d1699[24]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[30]), scm__rc.d1699[23]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[32]), scm__rc.d1699[22]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[34]), scm__rc.d1699[21]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[36]), scm__rc.d1699[1]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[42]), scm__rc.d1699[10]);
  scm__rc.d1699[46] = Scm_MakeExtendedPair(scm__rc.d1699[20], SCM_OBJ(&scm__rc.d1699[36]), SCM_OBJ(&scm__rc.d1699[44]));
  Scm_MakeBinding(SCM_MODULE(mod), SCM_SYMBOL(SCM_INTERN("do-verify")), SCM_OBJ(&jwteclib_do_verify__STUB), 0);
  jwteclib_do_verify__STUB.common.info = scm__rc.d1699[46];
  scm__rc.d1699[47] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[12])),TRUE); /* list-builtin-curves */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[52]), scm__rc.d1699[10]);
  scm__rc.d1699[56] = Scm_MakeExtendedPair(scm__rc.d1699[47], SCM_NIL, SCM_OBJ(&scm__rc.d1699[54]));
  Scm_MakeBinding(SCM_MODULE(mod), SCM_SYMBOL(SCM_INTERN("list-builtin-curves")), SCM_OBJ(&jwteclib_list_builtin_curves__STUB), 0);
  jwteclib_list_builtin_curves__STUB.common.info = scm__rc.d1699[56];
  scm__rc.d1699[57] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[13])),TRUE); /* test-pass-arg */
  scm__rc.d1699[58] = Scm_MakeSymbol(SCM_STRING(SCM_OBJ(&scm__sc.d1698[14])),TRUE); /* bn */
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[59]), scm__rc.d1699[58]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[61]), scm__rc.d1699[23]);
  SCM_SET_CAR(SCM_OBJ(&scm__rc.d1699[67]), scm__rc.d1699[10]);
  scm__rc.d1699[71] = Scm_MakeExtendedPair(scm__rc.d1699[57], SCM_OBJ(&scm__rc.d1699[61]), SCM_OBJ(&scm__rc.d1699[69]));
  Scm_MakeBinding(SCM_MODULE(mod), SCM_SYMBOL(SCM_INTERN("test-pass-arg")), SCM_OBJ(&jwteclib_test_pass_arg__STUB), 0);
  jwteclib_test_pass_arg__STUB.common.info = scm__rc.d1699[71];
}
