#!/usr/bin/env ruby

# TODO Before invoke the command, set RUBYLIB environment variable to ruby-jwt lib

require 'jwt'
require 'jwt/jwk'

privKeyfile = '/home/masa/src/github/ruby-jwt/spec/fixtures/certs/ec256-private.pem'
pubKeyfile = '/home/masa/src/github/ruby-jwt/spec/fixtures/certs/ec256-public.pem'

privateKey = OpenSSL::PKey.read File.read(privKeyfile)
publicKey = OpenSSL::PKey.read File.read(pubKeyfile)

sign = JWT.encode({"alg" => "ES256"}, privateKey, "ES256", {"iss"=>"joe", "exp"=>1300819380,"http://example.com/is_root"=>true});

print sign

print JWT.decode( sign, publicKey, true, algorithm: "ES256")

# TODO
# Check any algorithm
# Encode accept header and payload from stdin
# Decode accept one argument that is JWT string
